[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simple-wikidata-db"
dynamic = ["version"]
readme = "README.md"

dependencies = [
  "tqdm",
  "orjson",
  "pymongo",
  "typer",
]

[project.scripts]
copy-to-mongo = "simple_wikidata_db.copy_dump_to_mongodb:APP"

[tool.hatch.version]
path = "simple_wikidata_db/__version__.py"

[tool.hatch.build.targets.sdist]
include = [
    "simple_wikidata_db",
]

[tool.hatch.build.targets.wheel]
packages = ["simple_wikidata_db"]

[tool.ruff]
line-length=100

[tool.ruff.lint]
select = [
    # pycodestyle
    "E", "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
ignore=[
  # Do not suggest ternary operator
  "SIM108",
  # allow f-string in exception constructor
  "TRY003",
]
