[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simple-wikidata-db"
dynamic = ["version"]
readme = "README.md"

dependencies = [
  "tqdm",
  "orjson",
  "pymongo",
]

[tool.hatch.version]
path = "simple_wikidata_db/__version__.py"

[tool.hatch.build.targets.sdist]
include = [
    "simple_wikidata_db",
]

[tool.hatch.build.targets.wheel]
packages = ["simple_wikidata_db"]
